### ISSUE TITLE
Give Players Additional Useful Vote commands

### ISSUE THREAD

**Issue by HighCookie** [jacob404/promod-future#146]
I was watching a cast and they had some sort of bug that needed a map restart and scores set and tank and witch spawn moved and they couldn't do it without an admin.

I think adding votes to allow
Setting Tank
Setting Tank Player
Setting Witch
Setting Scores
Changing Slots (with some sort of enable flag)
Kicking All Specs (or just non-caster specs)

**Comment by jacob404** [comment]
pretty much all of these exist now
